# Generated by Django 5.0.4 on 2024-05-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_desc', models.TextField()),
                ('blog_category', models.CharField(max_length=50)),
                ('blog_image', models.FileField(blank=True, upload_to='blog_images/')),
                ('blog_views_count', models.IntegerField(max_length=20)),
                ('blog_likes_count', models.IntegerField(max_length=20)),
            ],
        ),
    ]
