# Generated by Django 5.0.4 on 2024-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_likes_count',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_views_count',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
